export const locations = [
  { name: "Toronto" },
  { name: "Mumbai" },
  { name: "Barcelona" },
  { name: "Moscow" },
  { name: "Chittagong" },
  { name: "Shenzhen" },
  { name: "Yerevan" },
  { name: "Foshan" },
  { name: "Pyongyang" },
  { name: "İzmir" },
  { name: "Baku" },
  { name: "Lahore" },
  { name: "Nagoya" },
  { name: "Dongguan" },
  { name: "Jakarta" },
  { name: "Kawasaki" },
  { name: "Porto Alegre" },
  { name: "Córdoba" },
  { name: "Salvador" },
  { name: "Tokyo" },
  { name: "Qom" },
  { name: "Sana'a" },
  { name: "Munich" },
  { name: "São Paulo" },
  { name: "Santiago" },
  { name: "Xiamen" },
  { name: "Tripoli" },
  { name: "Kanpur" },
  { name: "Hanoi" },
  { name: "Rosario" },
  { name: "Rio de Janeiro" },
  { name: "Bangkok" },
  { name: "Giza" },
  { name: "Douala" },
  { name: "Calgary" },
  { name: "Yaoundé" },
  { name: "Pune" },
  { name: "Hiroshima" },
  { name: "Buenos Aires" },
  { name: "Davao City" },
  { name: "Warsaw" },
  { name: "Lagos" },
  { name: "Kwangju,Korea" },
  { name: "Cape Town" },
  { name: "Chennai" },
  { name: "Mexico City" },
  { name: "Medellin" },
  { name: "Tangshan" },
  { name: "Lanzhou" },
  { name: "Mumbai" },
  { name: "Karachi" },
  { name: "Lucknow" },
  { name: "Nanjing" },
  { name: "Dubai" },
  { name: "Ibadan" },
  { name: "Kinshasa" },
  { name: "Harbin" },
  { name: "Hamburg" },
  { name: "Toronto" },
  { name: "Guangzhou" },
  { name: "Tunis" },
  { name: "Hyderabad" },
  { name: "Jaipur" },
  { name: "Lima" },
  { name: "Phnom Penh" },
  { name: "Cali" },
  { name: "Dhaka" },
  { name: "Ningbo" },
  { name: "Dalian" },
  { name: "Suzhou" },
  { name: "Belgrade" },
  { name: "Daegu" },
  { name: "Kyoto" },
  { name: "Basra" },
  { name: "Visakhapatnam" },
  { name: "Sofia" },
  { name: "Kano" },
  { name: "Hefei" },
  { name: "Chicago" },
  { name: "Sydney" },
  { name: "Abu Dhabi" },
  { name: "Paris" },
  { name: "Tabriz" },
  { name: "Lusaka" },
  { name: "Baghdad" },
  { name: "Dallas" },
  { name: "Kampala" },
  { name: "Jeddah" },
  { name: "Chengdu" },
  { name: "Patna" },
  { name: "Shiraz" },
  { name: "Hong Kong" },
  { name: "Ahvaz" },
  { name: "Caloocan" },
  { name: "T'bilisi" },
  { name: "Surat" },
  { name: "Recife" },
  { name: "Ahmedabad" },
  { name: "Budapest" },
  { name: "Maracaibo" },
  { name: "Ekurhuleni" },
  { name: "Changsha" }
];
